[package]
name = "blink-pi"
version = "0.1.0"
authors = ["MorganR <roffmorgan@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
embedded-hal = "1.0.0-alpha.4"
linux-embedded-hal = "0.4.0-alpha.0"
